In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../datasets/FinalDF.csv')
df

,Id,CourseNameShort,Academy,City,City_Population,City_Type,Jobs in City,Languages,ProgrammeDuration,TuitionFees,To,Time,Frequency,Distance (km),Jobs in neighbour cities,NeighbourCity_Population,NeighbourCity_Type
0,8305,Computer Science,University Of Potsdam,potsdam,"1,85,750",City,62.0,English,4,0,berlin,24.0,2.5,26.14,1062.0,"37,55,251",Metropolitan City
1,8305,Computer Science,University Of Potsdam,potsdam,"1,85,750",City,62.0,English,4,0,wildau,60.0,1.0,40.21,1.0,"10,000",Small Town
2,8305,Computer Science,University Of Potsdam,potsdam,"1,85,750",City,62.0,English,4,0,bergholz-rehbrücke,6.0,2.0,7.05,0.0,"8,000",Small Town
3,4439,Computer Science,University Of Stuttgart,stuttgart,"6,32,865",City,723.0,English,4,NaN,tübingen,49.0,3.0,30.18,56.0,"91,077",City
4,4439,Computer Science,University Of Stuttgart,stuttgart,"6,32,865",City,723.0,English,4,NaN,heilbronn,38.0,2.0,40.56,171.0,"126,000",City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637,9595,Information Engineering,Technical University Of Munich,heilbronn,"126,000",City,171.0,English,4,0,pforzheim,82.5,1.0,46.95,20.0,"1,25,000",City
638,9595,Information Engineering,Technical University Of Munich,heilbronn,"126,000",City,171.0,English,4,0,esslingen am neckar,55.0,1.0,44.90,7.0,"95,000",City
639,3724,Forest Information Technology (FIT),Eberswalde University For Sustainable Development,eberswalde,"40,000",Small Town,0.0,English,4,0,berlin,34.0,1.0,45.12,1062.0,"37,55,251",Metropolitan City
640,3724,Forest Information Technology (FIT),Eberswalde University For Sustainable Development,eberswalde,"40,000",Small Town,0.0,English,4,0,wildau¹,95.0,1.0,58.24,NaN,NaN,NaN
641,6981,Satellite Technology (SaTec),Julius-Maximilians-Universität Würzburg,würzburg,"1,27,810",City,62.0,English,4,0,schweinfurt,24.0,2.0,36.44,11.0,"53,000",Medium Town

### Population to numeric

In [3]:
df['City_Population'] = df['City_Population'].str.replace(',', '').astype(float)
df['NeighbourCity_Population'] = df['NeighbourCity_Population'].str.replace(',', '').astype(float)

In [4]:
df['TuitionFees'] = df['TuitionFees'].replace(['Null', 'null'], None)

df['TuitionFees'] = df['TuitionFees'].str.replace(',', '').astype(float)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 642 entries, 0 to 641
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        642 non-null    int64
 1   CourseNameShort           642 non-null    object
 2   Academy                   642 non-null    object
 3   City                      642 non-null    object
 4   City_Population           642 non-null    float64
 5   City_Type                 642 non-null    object
 6   Jobs in City              642 non-null    float64
 7   Languages                 642 non-null    object
 8   ProgrammeDuration         642 non-null    int64
 9   TuitionFees               531 non-null    float64
 10  To                        642 non-null    object
 11  Time                      642 non-null    float64
 12  Frequency                 642 non-null    float64
 13  Distance (km)             642 non-null    float64
 14  Jobs in neighbour cities  631 non-null    float64
 15  NeighbourCity_Population  640 non-null    float64
 16  NeighbourCity_Type        640 non-null    object
dtypes: float64(8), int64(2), object(7)
memory usage: 85.4+ KB

###Feature Engineering

In [6]:
df['Job_Density_Neighbor'] = df['Jobs in neighbour cities'] / (df['NeighbourCity_Population'] + 1e-6)

df['Connectivity_Score'] = df['Frequency'] / (df['Time'] * df['Distance (km)'] + 1e-6)

city_type_weights = {'Metropolitan City': 3, 'City': 2, 'Small Town': 1}
df['City_Importance_Score'] = df['NeighbourCity_Type'].map(city_type_weights)

In [7]:
df

,Id,CourseNameShort,Academy,City,City_Population,City_Type,Jobs in City,Languages,ProgrammeDuration,TuitionFees,To,Time,Frequency,Distance (km),Jobs in neighbour cities,NeighbourCity_Population,NeighbourCity_Type,Job_Density_Neighbor,Connectivity_Score,City_Importance_Score
0,8305,Computer Science,University Of Potsdam,potsdam,185750.0,City,62.0,English,4,0.0,berlin,24.0,2.5,26.14,1062.0,3755251.0,Metropolitan City,0.000283,0.003985,3.0
1,8305,Computer Science,University Of Potsdam,potsdam,185750.0,City,62.0,English,4,0.0,wildau,60.0,1.0,40.21,1.0,10000.0,Small Town,0.000100,0.000414,1.0
2,8305,Computer Science,University Of Potsdam,potsdam,185750.0,City,62.0,English,4,0.0,bergholz-rehbrücke,6.0,2.0,7.05,0.0,8000.0,Small Town,0.000000,0.047281,1.0
3,4439,Computer Science,University Of Stuttgart,stuttgart,632865.0,City,723.0,English,4,NaN,tübingen,49.0,3.0,30.18,56.0,91077.0,City,0.000615,0.002029,2.0
4,4439,Computer Science,University Of Stuttgart,stuttgart,632865.0,City,723.0,English,4,NaN,heilbronn,38.0,2.0,40.56,171.0,126000.0,City,0.001357,0.001298,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637,9595,Information Engineering,Technical University Of Munich,heilbronn,126000.0,City,171.0,English,4,0.0,pforzheim,82.5,1.0,46.95,20.0,125000.0,City,0.000160,0.000258,2.0
638,9595,Information Engineering,Technical University Of Munich,heilbronn,126000.0,City,171.0,English,4,0.0,esslingen am neckar,55.0,1.0,44.90,7.0,95000.0,City,0.000074,0.000405,2.0
639,3724,Forest Information Technology (FIT),Eberswalde University For Sustainable Development,eberswalde,40000.0,Small Town,0.0,English,4,0.0,berlin,34.0,1.0,45.12,1062.0,3755251.0,Metropolitan City,0.000283,0.000652,3.0
640,3724,Forest Information Technology (FIT),Eberswalde University For Sustainable Development,eberswalde,40000.0,Small Town,0.0,English,4,0.0,wildau¹,95.0,1.0,58.24,NaN,NaN,NaN,NaN,0.000181,NaN
641,6981,Satellite Technology (SaTec),Julius-Maximilians-Universität Würzburg,würzburg,127810.0,City,62.0,English,4,0.0,schweinfurt,24.0,2.0,36.44,11.0,53000.0,Medium Town,0.000208,0.002287,NaN

###Normalization

In [8]:
from sklearn.preprocessing import MinMaxScaler

columns_to_scale = [
    'TuitionFees', 'Jobs in City', 'Jobs in neighbour cities', 
    'City_Population', 'NeighbourCity_Population', 'Time', 
    'Frequency', 'Distance (km)', 
    'Job_Density_Neighbor',
    'Connectivity_Score',
    'City_Importance_Score'

]

scaler = MinMaxScaler()
df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

In [9]:
df

,Id,CourseNameShort,Academy,City,City_Population,City_Type,Jobs in City,Languages,ProgrammeDuration,TuitionFees,To,Time,Frequency,Distance (km),Jobs in neighbour cities,NeighbourCity_Population,NeighbourCity_Type,Job_Density_Neighbor,Connectivity_Score,City_Importance_Score
0,8305,Computer Science,University Of Potsdam,potsdam,0.047181,City,0.058380,English,4,0.0,berlin,0.112948,0.190476,0.428692,0.661270,1.000000,Metropolitan City,0.061863,0.002616,1.0
1,8305,Computer Science,University Of Potsdam,potsdam,0.047181,City,0.058380,English,4,0.0,wildau,0.311295,0.047619,0.666441,0.000623,0.002397,Small Town,0.021875,0.000210,0.0
2,8305,Computer Science,University Of Potsdam,potsdam,0.047181,City,0.058380,English,4,0.0,bergholz-rehbrücke,0.013774,0.142857,0.106117,0.000000,0.001865,Small Town,0.000000,0.031789,0.0
3,4439,Computer Science,University Of Stuttgart,stuttgart,0.166530,City,0.680791,English,4,NaN,tübingen,0.250689,0.238095,0.496958,0.034869,0.023993,City,0.134502,0.001298,0.5
4,4439,Computer Science,University Of Stuttgart,stuttgart,0.166530,City,0.680791,English,4,NaN,heilbronn,0.190083,0.142857,0.672356,0.106476,0.033296,City,0.296875,0.000806,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637,9595,Information Engineering,Technical University Of Munich,heilbronn,0.031231,City,0.161017,English,4,0.0,pforzheim,0.435262,0.047619,0.780331,0.012453,0.033029,City,0.035000,0.000105,0.5
638,9595,Information Engineering,Technical University Of Munich,heilbronn,0.031231,City,0.161017,English,4,0.0,esslingen am neckar,0.283747,0.047619,0.745691,0.004359,0.025038,City,0.016118,0.000204,0.5
639,3724,Forest Information Technology (FIT),Eberswalde University For Sustainable Development,eberswalde,0.008275,Small Town,0.000000,English,4,0.0,berlin,0.168044,0.047619,0.749409,0.661270,1.000000,Metropolitan City,0.061863,0.000370,1.0
640,3724,Forest Information Technology (FIT),Eberswalde University For Sustainable Development,eberswalde,0.008275,Small Town,0.000000,English,4,0.0,wildau¹,0.504132,0.047619,0.971105,NaN,NaN,NaN,NaN,0.000053,NaN
641,6981,Satellite Technology (SaTec),Julius-Maximilians-Universität Würzburg,würzburg,0.031714,City,0.058380,English,4,0.0,schweinfurt,0.112948,0.142857,0.602737,0.006849,0.013851,Medium Town,0.045401,0.001472,NaN

###Features weighting

In [10]:
weights = {
    'Jobs in City': 0.0,
    'Job_Density_Neighbor':0.1,
    'Connectivity_Score':0.7,
    'City_Importance_Score':0.2,    
}

df['Recommendation_Score'] = (
    weights['Jobs in City'] * df['Jobs in City'] +
    weights['Job_Density_Neighbor'] * df['Job_Density_Neighbor'] +
    weights['Connectivity_Score'] * df['Connectivity_Score'] +
    weights['City_Importance_Score'] * df['City_Importance_Score'] 

)

###University Recommendation

In [11]:
recommended_universities = df.sort_values(by='Recommendation_Score', ascending=False)

recommended_universities[['CourseNameShort', 'Academy', 'City', 'Recommendation_Score']].head(20)

,CourseNameShort,Academy,City,Recommendation_Score
280,Master Of Science In Software Engineering,University Of Augsburg,augsburg,0.224189
344,MSc Artificial Intelligence And Machine Learning,Technical University Of Darmstadt,darmstadt,0.222113
35,Master Of Science In Computer Science,Bingen Technical University Of Applied Sciences,bingen am rhein,0.220727
319,Information Systems – MSc,University Of Cologne,köln,0.218384
468,Game Development And Research (MA),Technische Hochschule Köln (University Of Appl...,köln,0.218384
597,Applied IT Security,Ruhr-Universität Bochum,bochum,0.216690
108,Computer Science MSc,Ruhr-Universität Bochum,bochum,0.216690
408,Master'S In Digital Transformation (MDT),Dortmund University Of Applied Sciences And Arts,dortmund,0.216489
449,Master'S In Embedded Systems Engineering (ESE),Dortmund University Of Applied Sciences And Arts,dortmund,0.216489
540,Media Informatics,RWTH Aachen University,bonn,0.216437
29,Computer Science,University Of Bonn,bonn,0.216437
117,"Information Engineering And Computer Science, MSc",Rhine-Waal University Of Applied Sciences,kamp-lintfort,0.216401
455,"Usability Engineering, MSc",Rhine-Waal University Of Applied Sciences,kamp-lintfort,0.216401
192,Digital Sciences (MSc),Technische Hochschule Köln (University Of Appl...,gummersbach,0.216339
589,Autonomous Systems (MSc),Hochschule Bonn-Rhein-Sieg,sankt augustin,0.216317
25,Computer Science,University Of Bonn,bonn,0.212684
536,Media Informatics,RWTH Aachen University,bonn,0.212684
267,Artificial Intelligence And Data Science,Heinrich Heine University Düsseldorf,düsseldorf,0.211196
188,Digital Sciences (MSc),Technische Hochschule Köln (University Of Appl...,gummersbach,0.209775
242,Management & Data Science (MSc),Leuphana University Lüneburg,lüneburg,0.209560

###Examples

In [12]:

weights = {
    'Jobs in City': 0.25,
    'Job_Density_Neighbor':0.25,
    'Connectivity_Score':0.25,
    'City_Importance_Score':0.25,    
}


df['Recommendation_Score'] = (
    weights['Jobs in City'] * df['Jobs in City'] +
    weights['Job_Density_Neighbor'] * df['Job_Density_Neighbor'] +
    weights['Connectivity_Score'] * df['Connectivity_Score'] +
    weights['City_Importance_Score'] * df['City_Importance_Score'] 

)

In [13]:

recommended_universities = df.sort_values(by='Recommendation_Score', ascending=False)

recommended_universities[['CourseNameShort', 'Academy', 'City', 'Recommendation_Score']].head(20)

,CourseNameShort,Academy,City,Recommendation_Score
468,Game Development And Research (MA),Technische Hochschule Köln (University Of Appl...,köln,0.404360
319,Information Systems – MSc,University Of Cologne,köln,0.404360
303,Master'S In Project Management & Data Science,HTW Berlin University Of Applied Sciences,berlin,0.394617
504,CyberMACS (Erasmus Mundus) | Applied Cybersecu...,SRH Universities,berlin,0.394617
226,Professional IT Business & Digitalisation,HTW Berlin University Of Applied Sciences,berlin,0.394617
244,Computer Science – Cyber Security Or Big Data ...,SRH Universities,berlin,0.394617
267,Artificial Intelligence And Data Science,Heinrich Heine University Düsseldorf,düsseldorf,0.384673
431,Software Technology,Hochschule Für Technik Stuttgart - University ...,stuttgart,0.369618
126,Computational Linguistics,University Of Stuttgart,stuttgart,0.369618
4,Computer Science,University Of Stuttgart,stuttgart,0.369618
280,Master Of Science In Software Engineering,University Of Augsburg,augsburg,0.335440
408,Master'S In Digital Transformation (MDT),Dortmund University Of Applied Sciences And Arts,dortmund,0.335180
449,Master'S In Embedded Systems Engineering (ESE),Dortmund University Of Applied Sciences And Arts,dortmund,0.335180
166,High Integrity Systems (HIS),Frankfurt University Of Applied Sciences,frankfurt am main,0.331747
392,Master'S In Applied Data Science (MSc),Frankfurt School Of Finance & Management,frankfurt am main,0.331747
176,Data Science,Hamburg University Of Technology,hamburg,0.331570
257,MSc Intelligent Adaptive Systems (IAS),Universität Hamburg,hamburg,0.331570
430,Software Technology,Hochschule Für Technik Stuttgart - University ...,stuttgart,0.329148
125,Computational Linguistics,University Of Stuttgart,stuttgart,0.329148
3,Computer Science,University Of Stuttgart,stuttgart,0.329148

In [55]:

weights = {
    'Jobs in City': 0.1,
    'Job_Density_Neighbor':0.2,
    'Connectivity_Score':0.6,
    'City_Importance_Score':0.1,    
}


df['Recommendation_Score'] = (
    weights['Jobs in City'] * df['Jobs in City'] +
    weights['Job_Density_Neighbor'] * df['Job_Density_Neighbor'] +
    weights['Connectivity_Score'] * df['Connectivity_Score'] +
    weights['City_Importance_Score'] * df['City_Importance_Score'] 
)

In [56]:

recommended_universities = df.sort_values(by='Recommendation_Score', ascending=False)

recommended_universities[['CourseNameShort', 'Academy', 'City', 'Recommendation_Score']].head(20)

,CourseNameShort,Academy,City,Recommendation_Score
331,Digital Engineering (DigiEng),Otto Von Guericke University Magdeburg,magdeburg,0.204729
81,Visual Computing,Otto Von Guericke University Magdeburg,magdeburg,0.204729
463,MSc In Data & Knowledge Engineering,Otto Von Guericke University Magdeburg,magdeburg,0.204729
468,Game Development And Research (MA),Technische Hochschule Köln (University Of Appl...,köln,0.179515
319,Information Systems – MSc,University Of Cologne,köln,0.179515
431,Software Technology,Hochschule Für Technik Stuttgart - University ...,stuttgart,0.177937
126,Computational Linguistics,University Of Stuttgart,stuttgart,0.177937
4,Computer Science,University Of Stuttgart,stuttgart,0.177937
226,Professional IT Business & Digitalisation,HTW Berlin University Of Applied Sciences,berlin,0.167876
504,CyberMACS (Erasmus Mundus) | Applied Cybersecu...,SRH Universities,berlin,0.167876
244,Computer Science – Cyber Security Or Big Data ...,SRH Universities,berlin,0.167876
303,Master'S In Project Management & Data Science,HTW Berlin University Of Applied Sciences,berlin,0.167876
267,Artificial Intelligence And Data Science,Heinrich Heine University Düsseldorf,düsseldorf,0.164632
280,Master Of Science In Software Engineering,University Of Augsburg,augsburg,0.158273
344,MSc Artificial Intelligence And Machine Learning,Technical University Of Darmstadt,darmstadt,0.152165
449,Master'S In Embedded Systems Engineering (ESE),Dortmund University Of Applied Sciences And Arts,dortmund,0.150490
408,Master'S In Digital Transformation (MDT),Dortmund University Of Applied Sciences And Arts,dortmund,0.150490
166,High Integrity Systems (HIS),Frankfurt University Of Applied Sciences,frankfurt am main,0.147492
392,Master'S In Applied Data Science (MSc),Frankfurt School Of Finance & Management,frankfurt am main,0.147492
29,Computer Science,University Of Bonn,bonn,0.146114

In [72]:

weights = {
    'Jobs in City': 1,
    'Job_Density_Neighbor':2,
    'Connectivity_Score':6,
    'City_Importance_Score':1,    
}

def recommend_by_user_preference(weights, df):
    
    weights['Jobs in City'] = weights.get('Jobs in City') / 10
    weights['Job_Density_Neighbor'] = weights.get('Job_Density_Neighbor') / 10
    weights['Connectivity_Score'] = weights.get('Connectivity_Score') / 10
    weights['City_Importance_Score'] = weights.get('City_Importance_Score') / 10
    
    df['Recommendation_Score'] = (
    weights['Jobs in City'] * df['Jobs in City'] +
    weights['Job_Density_Neighbor'] * df['Job_Density_Neighbor'] +
    weights['Connectivity_Score'] * df['Connectivity_Score'] +
    weights['City_Importance_Score'] * df['City_Importance_Score']  
    )
    
    recommended_universities = df.sort_values(by='Recommendation_Score', ascending=False)

    recomendations = recommended_universities[['Academy', 'CourseNameShort', 'City', 'Recommendation_Score']].head(10)
    
    return recomendations

In [73]:
result = recommend_by_user_preference(weights, df)
result.rename(columns={'CourseNameShort': 'Course Name', 'Academy': 'University', 'City': 'City', 'Recommendation_Score': 'Recommendation Score'}, inplace=True)
result.index = np.arange(1, len(result) + 1)
result['City'] = result['City'].str.title()
result['Recommendation Score'] = result['Recommendation Score'].apply(lambda x: round(x * 100, 2))

In [74]:
result

,University,Course Name,City,Recommendation Score
1,Otto Von Guericke University Magdeburg,Digital Engineering (DigiEng),Magdeburg,20.47
2,Otto Von Guericke University Magdeburg,Visual Computing,Magdeburg,20.47
3,Otto Von Guericke University Magdeburg,MSc In Data & Knowledge Engineering,Magdeburg,20.47
4,Technische Hochschule Köln (University Of Appl...,Game Development And Research (MA),Köln,17.95
5,University Of Cologne,Information Systems – MSc,Köln,17.95
6,Hochschule Für Technik Stuttgart - University ...,Software Technology,Stuttgart,17.79
7,University Of Stuttgart,Computational Linguistics,Stuttgart,17.79
8,University Of Stuttgart,Computer Science,Stuttgart,17.79
9,HTW Berlin University Of Applied Sciences,Professional IT Business & Digitalisation,Berlin,16.79
10,SRH Universities,CyberMACS (Erasmus Mundus) | Applied Cybersecu...,Berlin,16.79

In [27]:
import pickle

In [28]:
pickle.dump(df.to_dict() ,open('university_by_user_dict.pkl','wb'))